<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <AssemblyName>tagconvert</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\IdSharp.Common\IdSharp.Common.csproj" />
    <ProjectReference Include="..\..\IdSharp.Tagging\IdSharp.Tagging.csproj" />
  </ItemGroup>
</Project>
